test/e2e/operator_test.go

e2e: SSO -> RODOO

---

cmd/run-once-duration-override/runoncedurationoverride.go
pkg/runoncedurationoverride/admission.go
test/e2e/operator_test.go

The exempt condition was reverted

Fix the exempt condition and set the restart policy in e2e

---

OWNERS

Set repository component to run-once-duration-override

---

README.md

fix incorrect restartPolicy in example yaml

---

pkg/runoncedurationoverride/mutator.go
test/e2e/operator_test.go

This PR picks the minimum value between RODOO value and 
`pod.spec.activeDeadlineSeconds` if pod spec already contains `activeDeadlineSeconds` field.

Use min if pod spec includes activeDeadlineSeconds

---

pkg/runoncedurationoverride/config.go

This PR fixes a code scan warning for RODO.

Fix code scan warning

---

Makefile

OCPBUGS-25123: Makefile: add strictfipsruntime build tag

---

Makefile

NO-JIRA: Sync with master

---

Dockerfile

WRKLDS-1505: Dockerfile for operand

---

Dockerfile

no-jira: Sync with main

---

.tekton/run-once-duration-override-4-18-pull-request.yaml
.tekton/run-once-duration-override-4-18-push.yaml

WRKLDS-1505: [tekton]: build source image, hermetic builds, extend the list of archs

---

Dockerfile

no-jira: Fix dockerfile

---

.tekton/run-once-duration-override-4-18-pull-request.yaml
.tekton/run-once-duration-override-4-18-push.yaml

no-jira: [tekton]: enable snyk

---

Dockerfile

no-jira: [konflux] Dockerfiles for operand

---

.tekton/run-once-duration-override-4-16-pull-request.yaml
.tekton/run-once-duration-override-4-16-push.yaml

no-jira: [tekton]: build source image, hermetic builds, extend the list of archs

---

.tekton/run-once-duration-override-4-18-pull-request.yaml
.tekton/run-once-duration-override-4-18-push.yaml

no-jira: [tekton]: extend operand configs with required tasks

---

.tekton/run-once-duration-override-4-18-pull-request.yaml
.tekton/run-once-duration-override-4-18-push.yaml

no-jira: bump(.tekton)=release-4.19

---

Dockerfile

no-jira: Dockerfile: fix path to LICENSE file

---

.tekton/run-once-duration-override-4-18-pull-request.yaml
.tekton/run-once-duration-override-4-18-push.yaml

no-jira: Update the latest tekton changes

---

renovate.json

This PR disables auto package update in go.mod by Konflux. This is very redundant and noisy and waste of resources.

NO-JIRA: Disable auto update of packages in go.mod

---

README.md

chore: no-op: re-trigger pipeline

---

.tekton/run-once-duration-override-4-19-pull-request.yaml
.tekton/run-once-duration-override-4-19-push.yaml

feat(.tekton): update configuration according to the latest Konflux changes

---

.tekton/run-once-duration-override-4-20-pull-request.yaml
.tekton/run-once-duration-override-4-20-push.yaml

feat(.tekton): specify pathChanged()

---

.tekton/run-once-duration-override-4-20-push.yaml

no-jira: fix(.tekton): fix job name to push

---

.tekton/run-once-duration-override-main-pull-request.yaml
.tekton/run-once-duration-override-main-push.yaml

chore(.tekton): align with the main branch

---

.tekton/run-once-duration-override-4-19-pull-request.yaml
.tekton/run-once-duration-override-4-19-push.yaml

feat(.tekton): extend on-cel-expression
